### PR TITLE
automatic_setup init

### PR DESCRIPTION
**Pull request by jayp0521**

### CODE REVIEW

**Comment by jayp0521** [comment]
@mehalter, this should be ready. will do some more testing tomorrow, but everything is working as far as i can tell

**Comment by mehalter** [comment]
Cool I'll take a look in the morning! Thanks for a your help with this stuff @jayp0521 !

**Comment by mehalter** [comment]
Did some testing and it looks to work as expected! Didn't test all of the features  like limiting the types of sources, but the basic functionality seems to be great. Thanks again!

**Comment by jayp0521** [comment]
yes, i had tested that @mehalter. merging, thanks

**Comment by mehalter** [comment]
Awesome thanks! I'll get AstroNvim updated tomorrow!

**Pull request merged**
