### PR TITLE
Port mason lsp config features

### PR DESCRIPTION
**Pull request by jayp0521**
This PR is this [PR](https://github.com/jayp0521/mason-null-ls.nvim/pull/5) with the revival of `automatic_installation`

### CODE REVIEW

**Comment by jayp0521** [comment]
@RaafatTurki do you mind taking a look?

I will squash your commits into one and mine into another one before merging

**Comment by jayp0521** [comment]
@williamboman in case you have any feedback

**Comment by RaafatTurki** [comment]
Hey, I couldn't get `automatic_installation` to work but all others features seem to be working fine

here's the config I've tried
```lua
  local null_ls = require 'null-ls'
  null_ls.setup {
    null_ls.builtins.formatting.jq
  }
  require 'mason-null-ls'.setup {
    automatic_installation = true,
  }
```
and `jq` didn't get installed, I'm I missing something?

Also you might want to add `automatic_installation` into the code snippets in the README

**Comment by jayp0521** [comment]
> Hey, I couldn't get `automatic_installation` to work but all others features seem to be working fine
> 
> here's the config I've tried
> ```lua
>   local null_ls = require 'null-ls'
>   null_ls.setup {
>     null_ls.builtins.formatting.jq
>   }
>   require 'mason-null-ls'.setup {
>     automatic_installation = true,
>   }
> ```
> and `jq` didn't get installed, I'm I missing something?
> 
> Also you might want to add `automatic_installation` into the code snippets in the README

I'm on my phone. Haven't tested using your snippet, but isn't `require("mason").setup()` required to be called before this plugin to setup mason?

**Comment by RaafatTurki** [comment]
Correct, I do have it required elsewhere before my snippet executes, forgot to mention that here.

**Comment by jayp0521** [comment]
I think you need to put it in `sources`. Tested functionality. it seems to be working fine for me

```lua
  local null_ls = require 'null-ls'
  null_ls.setup {
    sources = {
        require("null-ls").builtins.formatting.jq,
    },
  }
  require 'mason-null-ls'.setup {
    automatic_installation = true,
  }
```

**Comment by jayp0521** [comment]
@RaafatTurki idk if you get alerted otherwise

**Comment by RaafatTurki** [comment]
> I think you need to put it in sources

hahah you're right, idk how I've missed that, it works just fine.

> idk if you get alerted otherwise

I got automatically subscribed to this PR, I get an email for every comment here ;3

**Pull request merged**
